# Generated by Django 3.2.3 on 2021-12-13 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChimesSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Chime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servo_offset', models.IntegerField(default=0)),
                ('kit_location', models.IntegerField()),
                ('note_name', models.CharField(max_length=10)),
                ('chimes_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.chimesset')),
            ],
        ),
    ]
